### PR TITLE
feat: Upgrading spring boot to v3

### LINKED ISSUE #257: Upgrade to Spring Boot 3.X
Migration guide: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide

### PR DESCRIPTION
**Pull request by Eddyhanderson**
The main changes was:
1 - Spring Security
  1.1 - Change deprecated method authorizeRequest to authorizeHttpRequests
  1.2 - Change method rename from antMatchers to requestMatchers

2 - Spring Data
  2.1 - In Hibernate 6 which is used by Spring 3, Ids are not generated (when using SEQUENCE strategy) using a unique sequence for all entities (called hibernate_sequence), instead it uses sequences for each specific entity. Because of that, it was creating duplicated Ids. To solve that, we use property **spring.jpa.properties.hibernate.id.db_structure_naming_strategy=single** to force hibernate using hibernate_sequence.

3 - Java version
  3.1 - Spring boot 3 requires Java 17+, so we need to change all javax references to jakarta

4 - Docker images
  4.1 - We need to change Spring container base image, to use Java 17+

5 - I think that it will be necessary to upgrade the JRE of the application server

 closes #257

### CODE REVIEW

**Comment by Nonononoki** [comment]
Any reason you changed the version to 1.1.0? It's mostly an internal version number anyway and not used at all

**Comment by Nonononoki** [comment]
Also, version 3.0.5 of Spring Boot has been released. Would be great if you could adjust that

**Comment by Eddyhanderson** [comment]
> Any reason you changed the version to 1.1.0? It's mostly an internal version number anyway and not used at all


I changed to indicate that we made a considerable change in app. Would you prefer not doing that ?

**Comment by Nonononoki** [comment]
> > Any reason you changed the version to 1.1.0? It's mostly an internal version number anyway and not used at all
> 
> I changed to indicate that we made a considerable change in app. Would you prefer not doing that ?

It doesn't really matter, but you also need to adjust all the scripts in the scripts folder

**Pull request merged**
