### PR TITLE
feat: Site customization CSS

### PR DESCRIPTION
**Pull request by peterzen**
This PR adds a `custom.css` file which is loaded after the default CSS.  This allows for implementing custom style rules.

### CODE REVIEW

**Comment by Nonononoki** [comment]
I'm not sure what this is suppose to do. What exactly is the goal here?

**Comment by peterzen** [comment]
> I'm not sure what this is suppose to do. What exactly is the goal here?

This is for the use case when the platform is being run on an own server and the operator wants to tweak the look and feel slightly (adjust colors etc).

**Comment by Nonononoki** [comment]
Can't they just tweak the alovoa.css?

**Comment by peterzen** [comment]
Having the local customizations in a separate file makes it easier to upgrade to the latest Alovoa versions.  CSS is notoriously hard to merge by hand :)

**Comment by Nonononoki** [comment]
I disagree, you can just place your custom css code at the bottom of alovoa.css, nothing hard about that ;)

**Comment by peterzen** [comment]
> I disagree, you can just place your custom css code at the bottom of alovoa.css, nothing hard about that ;)

Yeah you could do that and it works most of the time but there will be be conflicts every now and then :)  It's best practice to keep a separate file for local customizations.

**Comment by Nonononoki** [comment]
UI frontend moved to [alovoa-expo](https://github.com/Alovoa/alovoa-expo)

**Pull request closed without merging**
