### PR TITLE
feat: Email notifications for new likes, matches and messages

### PR DESCRIPTION
**Pull request by pranavbalakrishnan4100**
Addresses #342 

- Added a new entity UserSettings to User.java
- Added unified endpoint for all three user preferences under user settings .
- Created new email templates for all three cases.
- Added necessary test cases. 

Opened a [ticket](https://github.com/Alovoa/alovoa-expo/issues/37) in alovoa-expo to handle necessary front end changes.

### CODE REVIEW

**Comment by Nonononoki** [comment]
You need to remove the apache-maven folder

**Comment by pranavbalakrishnan4100** [comment]
Removed apache-maven folder.

**Comment by Nonononoki** [comment]
1. .gitignore has 1 unneeded extra line
2. Why have you added mysql dependencies?
3. UserController has a bunch of code commented out

**Comment by pranavbalakrishnan4100** [comment]
Latest changes updated.

Added mysql dependency to run using mysql in my machine.

**Comment by Nonononoki** [comment]
Please do not change .gitignore, place maven outside of the project instead. Looking good otherwise.

**Comment by pranavbalakrishnan4100** [comment]
Latest changes updated. Please have a look and approve.

**Comment by Nonononoki** [comment]
In UserController, please separate all 3 mail settings into individual endpoints. Also, please use PostMapping instead of PutMapping. Also consider creating a separate Controller class for the UserSettings alone.

**Comment by Nonononoki** [comment]
Member variables of UserSettings should all be private and should be used with a getter/setter.

**Comment by Nonononoki** [comment]
After some thought, the emailMatch should be _**scrapped**_.
The user who gives the like that leads to a match should **not** receive the match email.
The user who gets the like should _either_ get a like email **_OR_** a match email, but never both at the same time.

**Comment by pranavbalakrishnan4100** [comment]
My thought process behind the unified endpoint was that we might want to have the user settings page as a form. The form will have all the three values set as false when initialised. Whenever a user makes a change to one or more of these settings, we can once again create a UserSettings object with the new values and make the request.

If you insist on changing it, I can go ahead and do it.

**Comment by Nonononoki** [comment]
It's better to separate them.

**Comment by pranavbalakrishnan4100** [comment]
I've made the changes as discussed above. Kindly take a look at the UserSettings controller and let me know if its okay to directly update the email settings as I've done. Or do I need to create a seperate UserSettingsService and create a new method to do this?

**Comment by Nonononoki** [comment]
Spotted a few more issues:

- Rest end point shoud be "/user/settings" and not "/user-settings"
- UserSettingsController is completely wrong, new settings isn't being saved to database. Also RestController classes shoudn't have any logic in them, please create a new UserSettingsService 
- testUpdateUserSettings in UserServiceTest.java doesn't test anything at all. Please add tests for the new UserSettingsService and create a UserSettingsServiceTest instead of using the already bloated UserServiceTest

I just made a new commit for adding UserPrompt, you can use it as reference: 4f0ca1c630224ed44e4f6e09bfb55aaccf5f01b9

**Comment by pranavbalakrishnan4100** [comment]
Sure, I will make the necessary changes. Apologies for the oversight.
soon
Would you like me to make a UserSettingsDTO as well?

**Comment by pranavbalakrishnan4100** [comment]
Hopefully the changes are fine now. Sorry to keep this going back and forth.

**Comment by pranavbalakrishnan4100** [comment]
@Nonononoki I had a query that I was hoping you could answer.

Why do you insist on using @PostMapping instead of @PutMapping even when the api requests is specifiically an update operation? This seems to be pretty consistent across the codebase?
In the [commit](https://github.com/Alovoa/alovoa/commit/4f0ca1c630224ed44e4f6e09bfb55aaccf5f01b9) you have referenced above you seem to have used @PostMapping for delete operations as well? Was that intentional?

**Comment by pranavbalakrishnan4100** [comment]
Sure. Thanks for clarifying.

**Comment by pranavbalakrishnan4100** [comment]
@Nonononoki Thanks for the opportunity and guidance. This happens to be my first ever open source contribution. :)

**Pull request merged**
