### PR TITLE
Run tests in ci

### PR DESCRIPTION
**Pull request by fapdash**
- I"ve introduced Base64 encoding for the AES keys as I couldn't figure out how to pass them in UTF-8. Base64 is also the way I learned of how to pass keys and salts as strings / text.
  edit: I can revert this change if you want, but then it would be great if you could provide me with a key & salt.
- I expect the GH actions to break first, will probably need a bit of fiddling to get them right

### CODE REVIEW

**Comment by fapdash** [comment]
Looks like I got the GHA right with the first try, tested it out here:
- https://github.com/fapdash/alovoa/pull/1
- https://github.com/fapdash/alovoa/actions/runs/2024384856

**Comment by Nonononoki** [comment]
> I"ve introduced Base64 encoding for the AES keys

What's wrong with the current way to do it? Why is this an improvement?
Some randomly generated values for key and salt:
key: bqupWgmhCj3fedLxYdNAy2QFA2bS9XJX
salt: sFRKQAhwdrZq44FQ

**Comment by fapdash** [comment]
@Nonononoki I tried to generate a key and a salt like this, which is apparently completely wrong but I couldn't find out the correct way to do it.

```java
KeyGenerator gen = KeyGenerator.getInstance("AES");
gen.init(128);
SecretKey secret = gen.generateKey();
byte[] binary = secret.getEncoded();
System.out.println(new String(binary, StandardCharsets.UTF_8));

byte[] iv = new byte[16];
new SecureRandom().nextBytes(iv);	  
System.out.println(new String(iv, StandardCharsets.UTF_8));
```

How do you generate the keys?

**Comment by Nonononoki** [comment]
I just use Keepass to generate keys.
One note, the key must be 16, 24 or 32 characters long.
Salt is 16 characters long.

**Pull request merged**
