### PR TITLE
feat: gender update

### PR DESCRIPTION
**Pull request by RajivSingh-dev**
Added feature so user has option to change gender

### CODE REVIEW

**Comment by Nonononoki** [comment]
@RajivSingh-dev
1. The URL /user/update/**userGender**/ userGender is redundant, use _gender_ instead
2. As this is a feature most users won't use, it needs to be placed at the bottom. Preferably as a link (clickable text) with a modal with a dropdown/radio buttons.
3. There also needs a warning when changing the gender
4. Needs another new column in UserDates, changing gender needs a cooldown. Preferably 30 days.
5. Upon changing the gender, non-compatible likes and matches must be removed.
6. Needs a test for backend code.

**Comment by RajivSingh-dev** [comment]
I'm going throught it 
Thanks for the comment

**Comment by Nonononoki** [comment]
@RajivSingh-dev Please do not push that many times for every single change. Otherwise the bot will go through every commit and emails are being sent for every commit. You should commit locally, and if it seems like it could be reviewed, merge all small commits to one big one instead.

**Comment by RajivSingh-dev** [comment]
Sure from  next time i will take care of this i will make only appropriate no. of commits wherever required

**Comment by RajivSingh-dev** [comment]
@Nonononoki I'm done with the changes of this pr from my side u can review it when u have free time

**Comment by Nonononoki** [comment]
@RajivSingh-dev Please squash all of your commits into a single one

**Comment by RajivSingh-dev** [comment]
@Nonononoki i have quashed all commit into single Commit "Option to change gender"
From next time i will take care of while pushing commits and will make single commit for all changes
Thank you for your time and support . I'm really helpful to you for your guidance and support

**Comment by Nonononoki** [comment]
1. In updateUserGender() the 30 days are hardcoded. Use a constant instead.
2. New function diffInDays in ambiguous. Consider renaming it to diffInDaysFromToday.
3. Only likes are being removed. Conversations with non-compatible users should also be removed.
4. In the loop of deleting users, consider storing the to be deleted objects to a list and deleting them in a batch, calling the save method in a loop is very costly
5. JUnit tests are still missing. There are tests in UserServiceTest.java for reference.

**Pull request closed without merging**
